name: Blog posts
on:
  schedule:
    - cron: '0 * * * *'
    workflow_dispatch:
jobs:
  blog:
    name: latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
        comment_tag_name: "BLOG-POST-LIST"
          feed_list: 'https://medium.com/feed/@theBwoyPrgrmmr'